# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14l_MgG05-yg1aDujmwRQ1Putbr5XHC0x
"""
import pandas as pd
import numpy as np
import importlib
import ipywidgets as widgets
from IPython.display import display, clear_output
from openpyxl import load_workbook
from datetime import datetime
import shutil

def cargar_datos(ruta_excel):
    precios = pd.read_excel(ruta_excel, sheet_name='Precios_Sepultura')
    cuota = pd.read_excel(ruta_excel, sheet_name='CuotaDscto_Sepultura')
    foma = pd.read_excel(ruta_excel, sheet_name='FOMA')
    interes = pd.read_excel(ruta_excel, sheet_name='Interes')

    df = (
        precios
        .merge(
            cuota[['Tipo_espacio', 'Servicio_funerario', 'Meses', 'Descuento']],
            on=['Tipo_espacio', 'Servicio_funerario'],
            how='left'
        )
        .merge(
            foma,
            on='Tipo_espacio',
            how='left'
        )
    )

    return df, interes

def obtener_proforma(df, espacio, servicio):
    df_filtrado = df[
        (df["Tipo_espacio"] == espacio) &
        (df["Tipo_Servicio"] == servicio)
    ]

    if df_filtrado.empty:
        raise ValueError("No hay datos para la combinación seleccionada")

    return df_filtrado.iloc[0]

def calcular_financiamiento(row, interes_df):
    meses = int(row["Meses"])
    precio = float(row["Precio"])
    inicial = float(row["Inicial"])
    descuento = float(row["Descuento"])
    foma = int(row["FOMA"])

    neto = precio * (1 - descuento)
    financiado = neto - inicial

    lista_meses = list(range(meses, -1, -12))

    df_descenso = pd.DataFrame({
        "Meses": lista_meses,
        "Cuota mes": [
            round(financiado / m, 2) if m > 0 else financiado
            for m in lista_meses
        ]
    })

    df_descenso = (
        df_descenso
        .merge(interes_df[['Meses', 'Interes']], on='Meses', how='left')
        .fillna(0)
    )

    df_descenso['Interes'] = df_descenso['Interes'] * neto
    df_descenso["Cuota mes"] = (financiado - df_descenso["Interes"]) / df_descenso["Meses"]

    df_descenso["Cuota mes"] = df_descenso["Cuota mes"].replace(
        np.inf,
        (neto + foma - df_descenso["Interes"]).iloc[-1]
    )

    df_descenso["Meses"] = df_descenso["Meses"].apply(
        lambda x: "CONTADO" if x == 0 else f"{int(x)} CUOTAS"
    )

    return {
        "precio": round(precio, 2),
        "descuento": round(descuento, 2),
        "neto": round(neto, 2),
        "inicial": round(inicial, 2),
        "financiado": round(financiado, 2),
        "foma": foma,
        "df_descenso": df_descenso
    }

def exportar_proforma_excel(
    ruta_origen,
    ruta_salida,
    datos,
    df_descenso,
    espacio,
    cliente
):
    hoy = datetime.today().strftime("%m %d %Y")

    shutil.copy(ruta_origen, ruta_salida)
    wb = load_workbook(ruta_salida)
    ws = wb.active

    mapeo = {
        "D17": datos["precio"],
        "C18": datos["descuento"],
        "D18": datos["precio"] * datos["descuento"],
        "D19": datos["neto"],
        "D20": datos["inicial"],
        "D21": datos["financiado"],
        "E39": datos["foma"],
        "G9": hoy,
        "C5": espacio,
        "C7": "Venta Anticipada",

        "C10": cliente.get("nombre", ""),
        "C11": cliente.get("direccion", ""),
        "C12": cliente.get("correo", ""),
        "C13": cliente.get("telefono", ""),
        "C14": cliente.get("doc", "")
    }

    for celda, valor in mapeo.items():
        ws[celda] = valor

    ws["C18"].number_format = "0%"

    fila_inicio = 25
    col_inicio = 2

    for i, row in enumerate(df_descenso.itertuples(index=False)):
        for j, value in enumerate(row):
            ws.cell(
                row=fila_inicio + i,
                column=col_inicio + j,
                value=value
            )

    wb.save(ruta_salida)

def crear_widgets(df):
    espacio_opts = df["Tipo_espacio"].unique().tolist()
    servicio_opts = df["Tipo_Servicio"].unique().tolist()

    dd_espacio = widgets.Dropdown(
        options=espacio_opts,
        description='Espacio:'
    )

    dd_servicio = widgets.Dropdown(
        options=servicio_opts,
        description='Servicio:'
    )

    txt_nombre = widgets.Text(description='Nombre:')
    txt_direccion = widgets.Text(description='Dirección:')
    txt_correo = widgets.Text(description='Correo:')
    txt_telefono = widgets.Text(description='Teléfono:')
    txt_doc = widgets.Text(description='Doc. ID:')

    btn = widgets.Button(description="Generar proforma")
    output = widgets.Output()

    return (
        dd_espacio, dd_servicio,
        txt_nombre, txt_direccion, txt_correo, txt_telefono, txt_doc,
        btn, output
    )

def generar_proforma_event(
    df,
    interes,
    dd_espacio,
    dd_servicio,
    txt_nombre,
    txt_direccion,
    txt_correo,
    txt_telefono,
    txt_doc,
    output,
    ruta_plantilla,
    ruta_salida
):
    def _handler(b):
        with output:
            clear_output()

            espacio_sel = dd_espacio.value
            servicio_sel = dd_servicio.value

            cliente = {
                "nombre": txt_nombre.value.strip(),
                "direccion": txt_direccion.value.strip(),
                "correo": txt_correo.value.strip(),
                "telefono": txt_telefono.value.strip(),
                "doc": txt_doc.value.strip()
            }

            try:
                proforma = obtener_proforma(df, espacio_sel, servicio_sel)
                resultado = calcular_financiamiento(proforma, interes)

                exportar_proforma_excel(
                    ruta_origen=ruta_plantilla,
                    ruta_salida=ruta_salida,
                    datos=resultado,
                    df_descenso=resultado["df_descenso"],
                    espacio=espacio_sel,
                    cliente=cliente
                )

                print("Proforma generada correctamente")

            except Exception as e:
                print(f"Error: {e}")

    return _handler
